### ISSUE TITLE
Slack no longer supports offline mode

### ISSUE THREAD

**Issue by mastercoms** [CircuitSoftGroup/SlackMC#12]
We need to check for offline mode or switch back to usernames or have a config option so that people in offline mode can still have skins on Slack.

**Comment by Janmm14** [comment]
Just get the online uuid of that name from the mojang api described at wiki.vg/Mojang_API

**Comment by mastercoms** [comment]
I am worried about making too many web requests.

**Comment by mastercoms** [comment]
I might just move back to using names but with a different service.

**Comment by mastercoms** [comment]
Fixed.
