### ISSUE TITLE
connections only work in debug mode

### ISSUE THREAD

**Issue by mastercoms** [CircuitSoftGroup/SlackMC#5]
Since we need to store the connection response codes in order to complete the connection, and we only do that debug mode, people not using debug mode cannot use SlackMC.

Introduced in 1.4.1.

**Comment by mastercoms** [comment]
Fixed in 1.4.4.

**Comment by Dude17172009** [comment]
I had to re-enable debug in order to send messages to Slack in 1.5.0-beta1

**Comment by mastercoms** [comment]
That's weird because debug mode was removed in 1.5.0. I'll look into it.

**Comment by mastercoms** [comment]
I just searched the code and there was no mention of debug. What happens when you remove the debug-mode line all together?
