### ISSUE TITLE
Skin heads do not change in Slack.

### ISSUE THREAD

**Issue by Dude17172009** [CircuitSoftGroup/SlackMC#9]

**Comment by mastercoms** [comment]
This might be because of UUIDs, or cache.
Are you able to access with the updated skin head? https://cravatar.eu/head/INSERT_NICKNAME/128.png

**Comment by Dude17172009** [comment]
Yes.  That was to first thing I check to see if their skin was not updated there, but it is correct.

**Comment by mastercoms** [comment]
Ok, I will move to use UUIDs instead of player names in 1.5 to see if that helps.

**Comment by Dude17172009** [comment]
Got it! Thanks!

**Comment by mastercoms** [comment]
Check to see if the [latest dev build](https://github.com/CircuitSoftGroup/SlackMC/raw/master/Slack.jar) from 8f6a596395174fd279590361a7be30ea4b5bd311 fixes this.

**Comment by Dude17172009** [comment]
Yep, the heads were corrected!

**Comment by mastercoms** [comment]
Yay! :D
